<option value="{{ 'af' }}">{{ __('Afrikaans') }}</option>
<option value="{{ 'sq' }}">{{ __('Albanian - shqip') }}</option>
<option value="{{ 'am' }}">{{ __('Amharic - አማርኛ') }}</option>
<option value="{{ 'ar' }}">{{ __('Arabic - العربية') }}</option>
<option value="{{ 'an' }}">{{ __('Aragonese - aragonés') }}</option>
<option value="{{ 'hy' }}">{{ __('Armenian - հայերեն') }}</option>
<option value="a{{ 'st' }}">{{ __('Asturian - asturianu') }}</option>
<option value="{{ 'az' }}">{{ __('Azerbaijani - azərbaycan dili') }}</option>
<option value="{{ 'eu' }}">{{ __('Basque - euskara') }}</option>
<option value="{{ 'be' }}">{{ __('Belarusian - беларуская') }}</option>
<option value="{{ 'bn' }}">{{ __('Bengali - বাংলা') }}</option>
<option value="{{ 'bs' }}">{{ __('Bosnian - bosanski') }}</option>
<option value="{{ 'br' }}">{{ __('Breton - brezhoneg') }}</option>
<option value="{{ 'bg' }}">{{ __('Bulgarian - български') }}</option>
<option value="{{ 'ca' }}">{{ __('Catalan - català') }}</option>
<option value="c{{ 'kb' }}">{{ __('Central Kurdish - کوردی (دەستنوسی عەرەبی)') }}</option>
<option value="{{ 'zh' }}">{{ __('Chinese - 中文') }}</option>
<option value="zh-{{ 'HK' }}">{{ __('Chinese (Hong Kong) - 中文（香港）') }}</option>
<option value="zh-{{ 'CN' }}">{{ __('Chinese (Simplified) - 中文（简体）') }}</option>
<option value="zh-{{ 'TW' }}">{{ __('Chinese (Traditional) - 中文（繁體）') }}</option>
<option value="{{ 'co' }}">{{ __('Corsican') }}</option>
<option value="{{ 'hr' }}">{{ __('Croatian - hrvatski') }}</option>
<option value="{{ 'cs' }}">{{ __('Czech - čeština') }}</option>
<option value="{{ 'da' }}">{{ __('Danish - dansk') }}</option>
<option value="{{ 'nl' }}">{{ __('Dutch - Nederlands') }}</option>
<option value="{{ 'en' }}">{{ __('English') }}</option>
<option value="en-{{ 'AU' }}">{{ __('English (Australia)') }}</option>
<option value="en-{{ 'CA' }}">{{ __('English (Canada)') }}</option>
<option value="en-{{ 'IN' }}">{{ __('English (India)') }}</option>
<option value="en-{{ 'NZ' }}">{{ __('English (New Zealand)') }}</option>
<option value="en-{{ 'ZA' }}">{{ __('English (South Africa)') }}</option>
<option value="en-{{ 'GB' }}">{{ __('English (United Kingdom)') }}</option>
<option value="en-{{ 'US' }}">{{ __('English (United States)') }}</option>
<option value="{{ 'eo' }}">{{ __('Esperanto - esperanto') }}</option>
<option value="{{ 'et' }}">{{ __('Estonian - eesti') }}</option>
<option value="{{ 'fo' }}">{{ __('Faroese - føroyskt') }}</option>
<option value="f{{ 'il' }}">{{ __('Filipino') }}</option>
<option value="{{ 'fi' }}">{{ __('Finnish - suomi') }}</option>
<option value="{{ 'fr' }}">{{ __('French - français') }}</option>
<option value="fr-{{ 'CA' }}">{{ __('French (Canada) - français (Canada)') }}</option>
<option value="fr-{{ 'FR' }}">{{ __('French (France) - français (France)') }}</option>
<option value="fr-{{ 'CH' }}">{{ __('French (Switzerland) - français (Suisse)') }}</option>
<option value="{{ 'gl' }}">{{ __('Galician - galego') }}</option>
<option value="{{ 'ka' }}">{{ __('Georgian - ქართული') }}</option>
<option value="{{ 'de' }}">{{ __('German - Deutsch') }}</option>
<option value="de-{{ 'AT' }}">{{ __('German (Austria) - Deutsch (Österreich)') }}</option>
<option value="de-{{ 'DE' }}">{{ __('German (Germany) - Deutsch (Deutschland)') }}</option>
<option value="de-{{ 'LI' }}">{{ __('German (Liechtenstein) - Deutsch (Liechtenstein)') }}</option>
<option value="de-{{ 'CH' }}">{{ __('German (Switzerland) - Deutsch (Schweiz)') }}</option>
<option value="{{ 'el' }}">{{ __('Greek - Ελληνικά') }}</option>
<option value="{{ 'gn' }}">{{ __('Guarani') }}</option>
<option value="{{ 'gu' }}">{{ __('Gujarati - ગુજરાતી') }}</option>
<option value="{{ 'ha' }}">{{ __('Hausa') }}</option>
<option value="h{{ 'aw' }}">{{ __('Hawaiian - ʻŌlelo Hawaiʻi') }}</option>
<option value="{{ 'he' }}">{{ __('Hebrew - עברית') }}</option>
<option value="{{ 'hi' }}">{{ __('Hindi - हिन्दी') }}</option>
<option value="{{ 'hu' }}">{{ __('Hungarian - magyar') }}</option>
<option value="{{ 'is' }}">{{ __('Icelandic - íslenska') }}</option>
<option value="{{ 'id' }}">{{ __('Indonesian - Indonesia') }}</option>
<option value="{{ 'ia' }}">{{ __('Interlingua') }}</option>
<option value="{{ 'ga' }}">{{ __('Irish - Gaeilge') }}</option>
<option value="{{ 'it' }}">{{ __('Italian - italiano') }}</option>
<option value="it-{{ 'IT' }}">{{ __('Italian (Italy) - italiano (Italia)') }}</option>
<option value="it-{{ 'CH' }}">{{ __('Italian (Switzerland) - italiano (Svizzera)') }}</option>
<option value="{{ 'ja' }}">{{ __('Japanese - 日本語') }}</option>
<option value="{{ 'kn' }}">{{ __('Kannada - ಕನ್ನಡ') }}</option>
<option value="{{ 'kk' }}">{{ __('Kazakh - қазақ тілі') }}</option>
<option value="{{ 'km' }}">{{ __('Khmer - ខ្មែរ') }}</option>
<option value="{{ 'ko' }}">{{ __('Korean - 한국어') }}</option>
<option value="{{ 'ku' }}">{{ __('Kurdish - Kurdî') }}</option>
<option value="{{ 'ky' }}">{{ __('Kyrgyz - кыргызча') }}</option>
<option value="{{ 'lo' }}">{{ __('Lao - ລາວ') }}</option>
<option value="{{ 'la' }}">{{ __('Latin') }}</option>
<option value="{{ 'lv' }}">{{ __('Latvian - latviešu') }}</option>
<option value="{{ 'ln' }}">{{ __('Lingala - lingála') }}</option>
<option value="{{ 'lt' }}">{{ __('Lithuanian - lietuvių') }}</option>
<option value="{{ 'mk' }}">{{ __('Macedonian - македонски') }}</option>
<option value="{{ 'ms' }}">{{ __('Malay - Bahasa Melayu') }}</option>
<option value="{{ 'ml' }}">{{ __('Malayalam - മലയാളം') }}</option>
<option value="{{ 'mt' }}">{{ __('Maltese - Malti') }}</option>
<option value="{{ 'mr' }}">{{ __('Marathi - मराठी') }}</option>
<option value="{{ 'mn' }}">{{ __('Mongolian - монгол') }}</option>
<option value="{{ 'ne' }}">{{ __('Nepali - नेपाली') }}</option>
<option value="{{ 'no' }}">{{ __('Norwegian - norsk') }}</option>
<option value="{{ 'nb' }}">{{ __('Norwegian Bokmål - norsk bokmål') }}</option>
<option value="{{ 'nn' }}">{{ __('Norwegian Nynorsk - nynorsk') }}</option>
<option value="{{ 'oc' }}">{{ __('Occitan') }}</option>
<option value="{{ 'or' }}">{{ __('Oriya - ଓଡ଼ିଆ') }}</option>
<option value="{{ 'om' }}">{{ __('Oromo - Oromoo') }}</option>
<option value="{{ 'ps' }}">{{ __('Pashto - پښتو') }}</option>
<option value="{{ 'fa' }}">{{ __('Persian - فارسی') }}</option>
<option value="{{ 'pl' }}">{{ __('Polish - polski') }}</option>
<option value="{{ 'pt' }}">{{ __('Portuguese - português') }}</option>
<option value="pt-{{ 'BR' }}">{{ __('Portuguese (Brazil) - português (Brasil)') }}</option>
<option value="pt-{{ 'PT' }}">{{ __('Portuguese (Portugal) - português (Portugal)') }}</option>
<option value="{{ 'pa' }}">{{ __('Punjabi - ਪੰਜਾਬੀ') }}</option>
<option value="{{ 'qu' }}">{{ __('Quechua') }}</option>
<option value="{{ 'ro' }}">{{ __('Romanian - română') }}</option>
<option value="{{ 'mo' }}">{{ __('Romanian (Moldova) - română (Moldova)') }}</option>
<option value="{{ 'rm' }}">{{ __('Romansh - rumantsch') }}</option>
<option value="{{ 'ru' }}">{{ __('Russian - русский') }}</option>
<option value="{{ 'gd' }}">{{ __('Scottish Gaelic') }}</option>
<option value="{{ 'sr' }}">{{ __('Serbian - српски') }}</option>
<option value="{{ 'sh' }}">{{ __('Serbo-Croatian - Srpskohrvatski') }}</option>
<option value="{{ 'sn' }}">{{ __('Shona - chiShona') }}</option>
<option value="{{ 'sd' }}">{{ __('Sindhi') }}</option>
<option value="{{ 'si' }}">{{ __('Sinhala - සිංහල') }}</option>
<option value="{{ 'sk' }}">{{ __('Slovak - slovenčina') }}</option>
<option value="{{ 'sl' }}">{{ __('Slovenian - slovenščina') }}</option>
<option value="{{ 'so' }}">{{ __('Somali - Soomaali') }}</option>
<option value="{{ 'st' }}">{{ __('Southern Sotho') }}</option>
<option value="{{ 'es' }}">{{ __('Spanish - español') }}</option>
<option value="es-{{ 'AR' }}">{{ __('Spanish (Argentina) - español (Argentina)') }}</option>
<option value="es-4{{ '19' }}">{{ __('Spanish (Latin America) - español (Latinoamérica)') }}</option>
<option value="es-{{ 'MX' }}">{{ __('Spanish (Mexico) - español (México)') }}</option>
<option value="es-{{ 'ES' }}">{{ __('Spanish (Spain) - español (España)') }}</option>
<option value="es-{{ 'US' }}">{{ __('Spanish (United States) - español (Estados Unidos)') }}</option>
<option value="{{ 'su' }}">{{ __('Sundanese') }}</option>
<option value="{{ 'sw' }}">{{ __('Swahili - Kiswahili') }}</option>
<option value="{{ 'sv' }}">{{ __('Swedish - svenska') }}</option>
<option value="{{ 'tg' }}">{{ __('Tajik - тоҷикӣ') }}</option>
<option value="{{ 'ta' }}">{{ __('Tamil - தமிழ்') }}</option>
<option value="{{ 'tt' }}">{{ __('Tatar') }}</option>
<option value="{{ 'te' }}">{{ __('Telugu - తెలుగు') }}</option>
<option value="{{ 'th' }}">{{ __('Thai - ไทย') }}</option>
<option value="{{ 'ti' }}">{{ __('Tigrinya - ትግርኛ') }}</option>
<option value="{{ 'to' }}">{{ __('Tongan - lea fakatonga') }}</option>
<option value="{{ 'tr' }}">{{ __('Turkish - Türkçe') }}</option>
<option value="{{ 'tk' }}">{{ __('Turkmen') }}</option>
<option value="{{ 'tw' }}">{{ __('Twi') }}</option>
<option value="{{ 'uk' }}">{{ __('Ukrainian - українська') }}</option>
<option value="{{ 'ur' }}">{{ __('Urdu - اردو') }}</option>
<option value="{{ 'ug' }}">{{ __('Uyghur') }}</option>
<option value="{{ 'uz' }}">{{ __('Uzbek - o‘zbek') }}</option>
<option value="{{ 'vi' }}">{{ __('Vietnamese - Tiếng Việt') }}</option>
<option value="{{ 'wa' }}">{{ __('Walloon - wa') }}</option>
<option value="{{ 'cy' }}">{{ __('Welsh - Cymraeg') }}</option>
<option value="{{ 'fy' }}">{{ __('Western Frisian') }}</option>
<option value="{{ 'xh' }}">{{ __('Xhosa') }}</option>
<option value="{{ 'yi' }}">{{ __('Yiddish') }}</option>
<option value="{{ 'yo' }}">{{ __('Yoruba - Èdè Yorùbá') }}</option>
<option value="{{ 'zu' }}">{{ __('Zulu - isiZulu') }}</option>
